apps/cart/urls.py
from django.contrib import admin
from django.urls import path, include

from .views import CartAddView, CartInfoView,CartUpdateView,CartDeleteView
app_name = 'cart'
urlpatterns = [
    path('add/', CartAddView.as_view(), name='add'),  # 购物车模块
    path('info/', CartInfoView.as_view(), name='show'), # 返回页面
    path('update/', CartUpdateView.as_view(), name='update'), # 购物车记录更新
    path('delete/', CartDeleteView.as_view(), name='delete'), # 删除购物车记录
]

apps/goods/urls.py
# -*- coding:utf-8 -*-
from django.contrib import admin
from django.urls import path, include, re_path
from apps.goods import views
from apps.goods.views import IndexView, DetailView,ListView

app_name = 'goods'
urlpatterns = [
    path('index/', IndexView.as_view(), name='index'),  # 首页
    path('goods/<str:goods_id>', DetailView.as_view(), name='detail'),  # 详情页
    path('list/<int:type_id>/<int:page>', ListView.as_view(), name='list'),  # 列表页
]

apps/user/urls.py
# -*- coding:utf-8 -*-
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.urls import path, include
from ..user import views
from ..user.views import *
app_name = 'user'
urlpatterns = [
    path('register/',RegisterView.as_view(),name='register'),
    path('active/<str:token>',ActiveView.as_view(),name='active'),
    path('login/',LoginView.as_view(),name='login'),
    path('logout/',LogoutView.as_view(),name='logout'),
    path('info/',UserInfoView.as_view(),name='info'),
    path('order/<int:page>',UserOrderView.as_view(),name='order'),
    path('site/',UserAddressView.as_view(),name='address'),
]

dailyfresh/urls.py
# -*- coding:utf-8 -*-
import haystack
from django.contrib import admin
from django.urls import path, include

urlpatterns=[
    path('admin/', admin.site.urls),
    path('tinymce/', include('tinymce.urls')),
    path('user/', include('apps.user.urls', namespace='user'),),  # 用户模块
    path('cart/', include('apps.cart.urls', namespace='cart'),),  # 购物车模块
    path('order/', include('apps.order.urls')),  # 订单模块
    path('goods/', include('apps.goods.urls')),  # 商品模块
    path('search/', include('haystack.urls')),  # 全文检索框架
]

apps/cart/models.py
from django.db import models

# Create your models here.

apps/cart/views.py
from django.shortcuts import render
from django.views.generic import View
from django.http import JsonResponse
from django_redis import get_redis_connection
from utils.mixin import LoginRequiredMixin
from ..goods.models import GoodsSKU

# Create your views here.
# 添加商品到购物车
# 请求方式 ajax post
# 如果涉及数据的增删改，则post方式，否则get方式
# 传递的参数：商品id(sku_id) 商品数量(count)
# /cart/add



class CartAddView(View):
    '''购物车记录添加'''

    def post(self, request):
        '''购物车记录添加'''
        user = request.user
        if not user.is_authenticated:
            return JsonResponse({'res': 0, 'errmsg': '请先登录'})
        # 接收数据
        sku_id = request.POST.get('sku_id')
        count = request.POST.get('count')
        # 数据校验
        if not all([sku_id, count]):
            return JsonResponse({'res': 1, 'errmsg': '数据不完整'})
        # 检验商品数量是否正确
        try:
            count = int(count)
        except Exception as e:
            return JsonResponse({'res': 2, 'errmsg': '商品数目出错'})
        # 校验商品是否存在
        try:
            sku = GoodsSKU.objects.get(id=sku_id)
        except GoodsSKU.DoesNotExist:
            # 商品不存在
            return JsonResponse({'res': 3, 'errmsg': '商品不存在'})
        # 业务处理
        # 1.先获取购物车记录
        conn = get_redis_connection('default')
        cart_key = 'cart_%d' % user.id
        # 先尝试获取sku_id的值，如果sku_id在hash中不存在，hget返回None
        cart_count = conn.hget(cart_key, sku_id)
        if cart_count:
            # 累加购物车中商品数目
            count += int(cart_count)
        # 检验商品库存
        if count > sku.stock:
            return JsonResponse({'res': 4, 'errmsg': '商品库存不足'})
        # 设置hash中sku_id的值,hset方法如果key存在，更新，如果不存在，则新增
        conn.hset(cart_key, sku_id, count)
        total_count = conn.hlen(cart_key)
        # 返回应答
        return JsonResponse({'res': 5, 'total_count':total_count,'errmsg': '添加成功'})


# /cart/info/
class CartInfoView(LoginRequiredMixin,View):
    def get(self,request):
        user = request.user
        # 获取用户对应的商品信息
        # 获取redis数据库连接
        conn = get_redis_connection('default')
        # 组成用户的key
        cart_key = 'cart_%d' % user.id
        # 获取用户key下的所有信息,格式{商品id:商品数量}
        cart_dict = conn.hgetall(cart_key)
        skus = []
        total_price = 0
        total_count = 0
        # 遍历字典获取每个商品的详细信息
        for sku_id in cart_dict.keys():
            count = int(cart_dict[sku_id])
            sku_id = int(sku_id)
            # 根据商品id获取商品详细信息
            sku = GoodsSKU.objects.get(id=sku_id)
            # 计算商品小计
            amount = sku.price*int(count)
            # 动态给sku对象增加一个属性,保存小计
            sku.amount = amount
            # 动态给sku对象增加一个属性,保存商品数量
            sku.count = count
            total_count += int(count)
            total_price += amount
            skus.append(sku)
        # 组织上下文
        context = {
            'total_count' : total_count,
            'total_price' : total_price,
            'skus' : skus
        }
        return render(request, 'cart.html', context)


# 更新购物车中商品数量
# 采用ajax post请求,前端传过来的参数，商品id(sku_id)，商品数量(count)
# /cart/update
class CartUpdateView(View):
    def post(self, request):
        # 接收数据
        user = request.user
        if not user.is_authenticated:
            return JsonResponse({'res': 0, 'errmsg': '请先登录'})
        # 接收数据
        sku_id=request.POST.get('sku_id')
        count=request.POST.get('count')
        # 数据校验
        if not all([sku_id, count]):
            return JsonResponse({'res': 1, 'errmsg': '数据不完整'})
        # 检验商品数量是否正确
        try:
            count=int(count)
        except Exception as e:
            return JsonResponse({'res': 2, 'errmsg': '商品数目出错'})
        # 校验商品是否存在
        try:
            sku=GoodsSKU.objects.get(id=sku_id)
        except GoodsSKU.DoesNotExist:
            # 商品不存在
            return JsonResponse({'res': 3, 'errmsg': '商品不存在'})

        # 业务处理
        conn=get_redis_connection('default')
        cart_key='cart_%d' % user.id
        # 如果count大于商品库存，则不能更新
        if count > sku.stock:
            return JsonResponse({'res': 4, 'errmsg': '库存不足'})
        # 更新
        conn.hset(cart_key,sku_id,count)
        # 计算用户购物车中商品的总件数
        total_count = 0
        vals = conn.hvals(cart_key)
        for val in vals:
            total_count += int(val)
        # 返回结果
        return JsonResponse({'res': 5, 'total_count':total_count,'errmsg': '更新成功'})


# 删除购物车中商品
# 采用ajax post请求,前端传过来的参数，商品id(sku_id)
# /cart/delete
class CartDeleteView(View):

    def post(self,request):
        # 数据接收
        user = request.user
        if not user.is_authenticated:
            return JsonResponse({'res': 0, 'errmsg': '请先登录'})
        sku_id = request.POST.get('sku_id')

        # 数据校验
        if not sku_id:
            return JsonResponse({'res': 1, 'errmsg': '无效的商品id'})
        try:
            sku = GoodsSKU.objects.get(id=sku_id)
        except GoodsSKU.DoesNotExist:
            return JsonResponse({'res': 2, 'errmsg': '商品不存在'})
        # 业务处理
        conn = get_redis_connection('default')
        cart_key = 'cart_%d'% user.id
        conn.hdel(cart_key,sku_id)
        # 计算用户购物车中商品的总件数
        total_count=0
        vals = conn.hvals(cart_key)
        for val in vals:
            total_count += int(val)
        # 返回响应
        return JsonResponse({'res': 3, 'total_count': total_count, 'errmsg': '删除成功'})

templates/base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
{% load staticfiles %}
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
    {# 网页标题块 #}
	<title>{% block title %}{% endblock title %}</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main(1).css' %}">
	{# 网页顶部引入文件块 #}
    {% block topfiles %}{% endblock topfiles %}
</head>
<body>
{# 网页顶部欢迎信息块 #}
{% block header_con %}
	<div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到天天生鲜!</div>
			<div class="fr">
                {% if user.is_authenticated %}
				<div class="login_btn fl">
					欢迎您：<em>{{ user.username }}</em>
                    <span>|</span>
					<a href="{% url 'user:logout' %}">退出</a>
				</div>

                {% else %}
				<div class="login_btn fl">
					<a href="{% url 'user:login' %}">登录</a>
					<span>|</span>
					<a href="{% url 'user:register' %}">注册</a>
				</div>
                {% endif %}
				<div class="user_link fl">
					<span>|</span>
					<a href="{% url 'user:info' %}">用户中心</a>
					<span>|</span>
					<a href="{% url 'cart:show' %}">我的购物车</a>
					<span>|</span>
					<a href="{% url 'user:order' 1 %}">我的订单</a>
				</div>
			</div>
		</div>		
	</div>
{% endblock header_con %}
{# 网页顶部搜索框 #}
{% block search_bar %}
	<div class="search_bar clearfix">
		<a href="{% url 'goods:index' %} " class="logo fl"><img src="{% static 'images/logo.png' %}"></a>
		<div class="search_con fl">
            <form method="get" action="/search">
			    <input type="text" class="input_text fl" name="q" placeholder="搜索商品">
			    <input type="submit" class="input_btn fr" name="" value="搜索">
            </form>
		</div>
		<div class="guest_cart fr">
			<a href="{% url 'cart:show' %}" class="cart_name fl">我的购物车</a>
			<div class="goods_count fl" id="show_count">{{ cart_count }}</div>
		</div>
	</div>
{% endblock search_bar %}
{# 网页主体块 #}
{% block body %}{% endblock body %}
	<div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>		
		</div>
		<p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>
    {# 网页底部html元素块 #}
    {% block bottom %}{% endblock bottom %}
    {# 网页底部引入文件块 #}
	{% block bottomfiles %}{% endblock bottomfiles %}
</body>
</html>

templates/base_detail_list.html
{% extends 'base.html' %}
{% block body %}
<div class="navbar_con">
		<div class="navbar clearfix">
			<div class="subnav_con fl">
				<h1>全部商品分类</h1>
				<span></span>
				<ul class="subnav">
                    {% for type in types %}
					<li><a href="{% url 'goods:list' type.id 1 %}" class="{{ type.logo }}">{{ type.name }}</a></li>
                    {% endfor %}
				</ul>
			</div>
			<ul class="navlist fl">
				<li><a href="{% url 'goods:index' %}">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">手机生鲜</a></li>
				<li class="interval">|</li>
				<li><a href="">抽奖</a></li>
			</ul>
		</div>
	</div>
    {# 详情页，列表页主体内容块 #}
    {% block main_content %}{% endblock main_content %}
{% endblock body %}

templates/base_user_center.html
{% extends 'base_no_cart.html' %}
{# 用户中心3页面父模板 #}
{% block title %}天天生鲜-用户中心{% endblock title %}
{% block page_title %}用户中心{% endblock page_title %}
{% block body %}
    <div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="{% url 'user:info' %}"{% if page == 'info' %} class="active"{% endif %}>· 个人信息</a></li>
				<li><a href="{% url 'user:order' 1 %}"{% if page == 'order' %} class="active"{% endif %}>· 全部订单</a></li>
				<li><a href="{% url 'user:address' %}"{% if page == 'site' %} class="active"{% endif %}>· 收货地址</a></li>
			</ul>
		</div>
        {# 用户中心右侧内容块 #}
        {% block right_content %}{% endblock right_content %}
    </div>
{% endblock body %}

templates/detail.html
{% extends 'base_detail_list.html' %}
{% load staticfiles %}
	{% block title %}天天生鲜-商品详情{% endblock %}

	{% block main_content %}
        <div class="breadcrumb">
            <a href="#">全部分类</a>
            <span>></span>
            <a href="#">{{ sku.type.name }}</a>
            <span>></span>
            <a href="#">商品详情</a>
	    </div>

	<div class="goods_detail_con clearfix">
		<div class="goods_detail_pic fl" ><img style="height: 380px;width: 380px" src="{{ sku.image.url }}"></div>

		<div class="goods_detail_list fr">
			<h3>{{ sku.name }}</h3>
			<p>{{ sku.desc }}</p>
			<div class="prize_bar">
				<span class="show_pirze">¥<em>{{sku.price}}</em></span>
				<span class="show_unit">单  位：{{ sku.unite }}</span>
			</div>
			<div class="goods_num clearfix">
				<div class="num_name fl">数 量：</div>
				<div class="num_add fl">
					<input type="text" class="num_show fl" value="1">
					<a href="javascript:;" class="add fr">+</a>
					<a href="javascript:;" class="minus fr">-</a>	
				</div> 
			</div>
            <div>
                <p>其他规格：</p>
                {% for sku in same_spu_skus %}
                <li><a href="{% url 'goods:detail' sku.id %}">{{ sku.name }}</a></li>
                {% endfor %}
            </div>
			<div class="total">总价：<em>{{sku.price}}元</em></div>
			<div class="operate_btn">
                {% csrf_token %}
				<a href="javascript:;" class="buy_btn">立即购买</a>
				<a href="javascript:;" sku_id="{{ sku.id }}" class="add_cart" id="add_cart">加入购物车</a>
			</div>
		</div>
	</div>

	<div class="main_wrap clearfix">
		<div class="l_wrap fl clearfix">
			<div class="new_goods">
				<h3>新品推荐</h3>
				<ul>
                    {% for sku in new_skus %}
					<li>
						<a href="{% url 'goods:detail'  sku.id %}"><img src="{{ sku.image.url }}"></a>
						<h4><a href="{% url 'goods:detail'  sku.id %}">{{ sku.name }}</a></h4>
						<div class="prize">￥{{ sku.price }}</div>
					</li>
                    {% endfor %}
				</ul>
			</div>
		</div>

		<div class="r_wrap fr clearfix">
			<ul class="detail_tab clearfix">
				<li id="tab_content" class="active">商品介绍</li>
				<li id="tab_content1">评论</li>
			</ul>

			<div class="tab_content">
				<dl>
					<dt>商品详情：</dt>
					<dd>{{ sku.goods.detail|safe }} </dd>
				</dl>
			</div>
            <div class="tab_content1">
				<dl>
                    {% for order in sku_orders %}
					<dt>评论时间：{{ order.update_time }}&nbsp;&nbsp;评价人:{{ order.order.user.username }}</dt>
					<dd>评论:{{ order.comment }} </dd>
                    {% endfor %}
				</dl>
			</div>

		</div>
	</div>
    {% endblock main_content %}
	{% block bottom %}
	<div class="add_jump"></div>
    {% endblock bottom %}
{% block bottomfiles %}
	<script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %} "></script>
	<script type="text/javascript">
    //计算商品的总价格
    function update_goods_amount() {
        //价格
        const price = parseFloat($('.show_pirze').children('em').text());
        //数量
        const count = parseFloat($('.num_show').val())
        const amount = price*count
        $('.total').children('em').text(amount.toFixed(2)+'元')
    }
    //增加商品数量
    $('.add').click(function () {
        //获取商品数量并加1
        let count = parseInt($('.num_show').val())
        count+=1
        //设置增加后的商品数量
        $('.num_show').val(count)
        //同步修改总价
        update_goods_amount()
    })
    //减少商品数量
    $('.minus').click(function () {
        //获取商品数量并减1
        let count = parseInt($('.num_show').val()-1)
        if(count <= 0){
            count = 1
        }
        //设置减少后的商品数量
        $('.num_show').val(count)
        //同步修改总价
        update_goods_amount()
    })
    //手动输入商品数量
    $('.num_show').blur(function () {
        //获取用户输入的商品数量
        let count = $(this).val()
        if(isNaN(count) || count.trim().length==0 || count<=0){
            count = 1
        }
         $('.num_show').val(parseInt(count))
         //同步修改总价
        update_goods_amount()
    })
    //评论与商品详情介绍切换
    $('#tab_content').click(function () {
        $(this).attr('class','active')
        $('.tab_content').show()
        $('.tab_content1').hide()
        $('#tab_content1').removeAttr('class')
    })
    $('#tab_content1').click(function () {
        $(this).attr('class','active')
        $('.tab_content1').show()
        $('.tab_content').hide()
        $('#tab_content').removeAttr('class')
    })



        var $add_x = $('#add_cart').offset().top;
		var $add_y = $('#add_cart').offset().left;

		var $to_x = $('#show_count').offset().top;
		var $to_y = $('#show_count').offset().left;


		$('#add_cart').click(function(){
		    //获取商品数量与价格
            const sku_id = $(this).attr('sku_id')
            const count = $('.num_show').val()
            //alert(sku_id+":"+count)
            csrf = $('input[name="csrfmiddlewaretoken"]').val()
            params = {'sku_id':sku_id,'count':count,'csrfmiddlewaretoken':csrf}
            //发起ajax post请求，访问/cart/add,传递参数：sku_id count
            $.post('/cart/add/',params,function (data) {
                if(data.res == 5){
                    //添加成功
                    $(".add_jump").css({'left':$add_y+80,'top':$add_x+10,'display':'block'})
                    $(".add_jump").stop().animate({
				        'left': $to_y+7,
				        'top': $to_x+7},
				        "fast", function() {
					    $(".add_jump").fadeOut('fast',function(){
						    $('#show_count').html(data.total_count);
					});
                    $('#show_count').html(data.total_count);
                    //alert(data.total_count)
			});
                    //alert(data.errmsg)
                }else{
                    alert(data.errmsg)
                }
            })

		})
	</script>
	{% endblock bottomfiles %}

templates/index.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}天天生鲜-首页{% endblock title %}
{% block topfiles %}
    <script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"> </script>
    <script type="text/javascript" src="{% static 'js/jquery-ui.min.js' %}"> </script>
    <script type="text/javascript" src="{% static 'js/slide.js' %}"> </script>
{% endblock topfiles %}

{% block body %}
	<div class="center_con clearfix">
		<ul class="subnav fl">
            {% for type in types %}
			<li><a href="#model0{{ forloop.counter }}" class="{{ type.logo }}">{{type.name}}</a></li>
            {% endfor %}
		</ul>
		<div class="slide fl">
			<ul class="slide_pics">
                {% for  banner in goods_banners %}
                <li><a href="{% url 'goods:detail' banner.sku.id %}"><img src="{{ banner.image.url }}" alt="幻灯片"></a></li>
                {% endfor %}
			</ul>
			<div class="prev"></div>
			<div class="next"></div>
			<ul class="points"></ul>
		</div>
		<div class="adv fl">
            {% for banner in promotion_banners %}
			    <a href="{{ banner.url }}"><img src="{{ banner.image.url }}"></a>
            {% endfor %}
		</div>
	</div>
{% for type in types %}
	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model0{{ forloop.counter }}">{{ type.name }}</h3>
			<div class="subtitle fl">
				<span>|</span>
				{% for banner in type.title_banners %}
				    <a href="{% url 'goods:detail' banner.sku.id %}">{{ banner.sku.name }}</a>
                {% endfor %}
			</div>
			<a href="#" class="goods_more fr">查看更多 ></a>
		</div>

		<div class="goods_con clearfix">
			<div class="goods_banner fl"><img src="{{ type.image.url }}"></div>
			<ul class="goods_list fl">
                {% for banner in type.image_banners %}
                    <li>
                        <h4><a href="#">{{ banner.sku.name }}</a></h4>
                        <a href="{% url 'goods:detail' banner.sku.id %}"><img src="{{ banner.sku.image.url }}"></a>
                        <div class="prize">¥ {{ banner.sku.price }}</div>
                    </li>
                {% endfor %}

			</ul>
		</div>
	</div>
{% endfor %}
{% endblock body %}

templates/list.html
{% extends 'base_detail_list.html' %}
{% block title %}天天生鲜-列表页面{% endblock title %}
{% block main_content %}
	    <div class="breadcrumb">
            <a href="#">全部分类</a>
            <span>></span>
            <a href="#">{{ sku.type.name }}</a>
	    </div>

	<div class="main_wrap clearfix">
		<div class="l_wrap fl clearfix">
			<div class="new_goods">
				<h3>新品推荐</h3>
				<ul>
                    {% for sku in new_skus %}
					<li>
						<a href="{% url 'goods:detail'  sku.id %}"><img src="{{ sku.image.url }}"></a>
						<h4><a href="{% url 'goods:detail' sku.id %}">{{ sku.name }}</a></h4>
						<div class="prize">￥{{ sku.price }}</div>
					</li>
					{% endfor %}
				</ul>
			</div>
		</div>

		<div class="r_wrap fr clearfix">
			<div class="sort_bar">
				<a href="{% url 'goods:list' type.id 1 %}" {% if sort == 'default' %}class="active"{% endif %}>默认</a>
				<a href="{% url 'goods:list' type.id 1 %}?sort=price" {% if sort == 'price' %}class="active"{% endif %}>价格</a>
				<a href="{% url 'goods:list' type.id 1 %}?sort=hot" {% if sort == 'hot' %}class="active"{% endif %}>人气</a>
			</div>

			<ul class="goods_type_list clearfix">
                {% for sku in skus_page %}
				<li>
					<a href="{% url 'goods:detail' sku.id %}"><img src="{{ sku.image.url }}"></a>
					<h4><a href="{% url 'goods:detail' sku.id %}">{{ sku.name }}</a></h4>
					<div class="operate">
						<span class="prize">￥{{sku.price}}</span>
						<span class="unit">{{ sku.price }}/{{ sku.unite }}</span>

					</div>
				</li>
                {% endfor %}

			</ul>

			<div class="pagenation">
                {% if skus_page.has_previous %}
				<a href="{% url 'goods:list' type.id skus_page.previous_page_number %}?sort={{ sort }}"><上一页</a>
                {% endif %}
                {% for pindex in pages %}
                    {% if pindex == skus_page.number %}
                        <a href="{% url 'goods:list' type.id pindex %}?sort={{ sort }}" class="active">{{ pindex }}</a>
                    {% else %}
                        <a href="{% url 'goods:list' type.id pindex %}?sort={{ sort }}">{{ pindex }}</a>
                    {% endif %}
                {% endfor %}
                {% if skus_page.has_next %}
				<a href="{% url 'goods:list' type.id skus_page.next_page_number %}?sort={{ sort }}">下一页></a>
                {% endif %}
			</div>
		</div>
	</div>

	{% endblock main_content %}

templates/place_order.html
{% extends 'base_no_cart.html' %}
{% load staticfiles %}
{% block title %}天天生鲜-提交订单{% endblock title %}
{% block page_title %}提交订单{% endblock page_title %}
{% block body %}

	<h3 class="common_title">确认收货地址</h3>

	<div class="common_list_con clearfix">
		<dl>
			<dt>寄送到：</dt>
            {% for addr in addrs %}
			<dd><input type="radio" name="addr_id" value="{{ addr.id }}" {% if addr.is_default %}checked {% endif %}>{{ addr.addr }} （{{ addr.receiver }} 收） {{ addr.phone }}</dd>
            {% endfor %}
		</dl>
		<a href="{% url 'user:address' %}" class="edit_site">编辑收货地址</a>

	</div>
	
	<h3 class="common_title">支付方式</h3>	
	<div class="common_list_con clearfix">
		<div class="pay_style_con clearfix">
			<input type="radio" name="pay_style" checked value="1">
			<label class="cash">货到付款</label>
			<input type="radio" name="pay_style" value="2">
			<label class="weixin">微信支付</label>
			<input type="radio" name="pay_style" value="3">
			<label class="zhifubao"></label>
			<input type="radio" name="pay_style" value="4">
			<label class="bank">银行卡支付</label>
		</div>
	</div>

	<h3 class="common_title">商品列表</h3>
	{% csrf_token %}
	<div class="common_list_con clearfix">
		<ul class="goods_list_th clearfix">
			<li class="col01">商品名称</li>
			<li class="col02">商品单位</li>
			<li class="col03">商品价格</li>
			<li class="col04">数量</li>
			<li class="col05">小计</li>		
		</ul>
        {% for sku in skus %}
		<ul class="goods_list_td clearfix">
			<li class="col01">{{ forloop.counter }}</li>
			<li class="col02"><img src="{{ sku.image.url }}"></li>
			<li class="col03">{{ sku.name }}</li>
			<li class="col04">{{ sku.unite }}</li>
			<li class="col05">{{ sku.price }}元</li>
			<li class="col06">{{ sku.count }}</li>
			<li class="col07">{{ sku.amount }}元</li>
		</ul>
		{% endfor %}
	</div>

	<h3 class="common_title">总金额结算</h3>

	<div class="common_list_con clearfix">
		<div class="settle_con">
			<div class="total_goods_count">共<em>{{ total_count }}</em>件商品，总金额<b>{{ total_price }}元</b></div>
			<div class="transit">运费：<b>{{ transit_price }}元</b></div>
			<div class="total_pay">实付款：<b>{{ total_pay }}元</b></div>
		</div>
	</div>

	<div class="order_submit clearfix">
		<a href="javascript:;" sku_ids = {{ sku_ids }} id="order_btn">提交订单</a>
	</div>	

{% endblock body %}
{% block bottom %}
	<div class="popup_con">
		<div class="popup">
			<p>订单提交成功！</p>
		</div>
		
		<div class="mask"></div>
	</div>
{% endblock bottom %}
    {% block bottomfiles %}
         <script src="{% static 'js/jquery-1.12.4.min.js' %}" > </script>
        <script type="text/javascript">
            $('#order_btn').click(function() {
                // 获取用户选择的地址id,支付方式,要购买的商品id
                let addr_id = $('input[name="addr_id"]:checked').val();
                let pay_method = $('input[name="pay_style"]:checked').val();
                let sku_ids = $(this).attr('sku_ids');

                let csrf = $('input[name="csrfmiddlewaretoken"]').val();
                //alert(addr_id+';'+pay_method+";"+sku_ids+";");
                // 发起ajax post请求,传递参数context
                params = {
                        'addr_id':addr_id,
                        'pay_method':pay_method,
                        'sku_ids':sku_ids,
                        'csrfmiddlewaretoken':csrf
                }
                $.post('/order/commit/',params,function (data) {
                    if(data.res == 5){
                        //创建成功
                       localStorage.setItem('order_finish',2);

                        $('.popup_con').fadeIn('fast', function() {
                            setTimeout(function(){
                                $('.popup_con').fadeOut('fast',function(){
                                    window.location.href = '/user/order/1';
                                });
                            },3000)

                        });
                    }else{
                        alert(data.errmsg);
                    }
                })

            });
        </script>
    {% endblock bottomfiles %}